# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47901096c3839b241db9a3a17926724c4baa96be44d7014ddc10e0137e860851d56d80480537b299c49e1aae41780213f51fa63b819429a92ee0eb0c25b35c1f

test:
  secret_key_base: 26bfdc15f76436740dbdd0b0a2fdcf3dc8cbe00e4d5e2f5d7e309aa71466f4f2cffd0445ecd4680d0b2e20c5e24b7a6659fd7f8c35fca695c44d2e17a0ab6b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
